name: pubspec_parse
description: >-
  Simple package for parsing pubspec.yaml files with a type-safe API and rich
  error reporting.
version: 0.1.2+3
homepage: https://github.com/dart-lang/pubspec_parse
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  # Verified that no new features since 1.0.0 are used - be careful!
  json_annotation: '>=1.0.0 <3.0.0'
  pub_semver: ^1.3.2
  yaml: ^2.1.12

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.0.0
  json_serializable: ^1.2.1
  path: ^1.5.1
  stack_trace: ^1.9.2
  test: ^1.0.0
  test_descriptor: ^1.0.3
  test_process: ^1.0.2
